/*
 * This source file was generated by the Gradle 'init' task
 */
package org.flashcard;


import org.flashcard.gui.*;

public class App {
    private static Gui gui;

    public static void main(String[] args) {
        


        gui = new Gui();

    }


}
