/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.4.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    testImplementation(libs.junit)

    // This dependency is used by the application.
    implementation(libs.guava)
    implementation(libs.sqlite.jdbc)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    // Ensure the java.desktop module is available at runtime for Swing.
    mainClass.set("org.flashcard.App")
    applicationDefaultJvmArgs = listOf("--add-modules", "java.desktop")
}

tasks.withType<Test>().configureEach {
    // Ensure Swing classes are available when running tests.
    jvmArgs("--add-modules", "java.desktop")
}
